// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/14/2026, 11:45:19 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/snajeekumar/Downloads/nexora-studio-fixed/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/components/global/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/plugins/**/*.{js,ts,mjs}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/composables/**/*.{js,ts,mjs}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/utils/**/*.{js,ts,mjs}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/pages/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/app.config.{js,ts,mjs}"]}},
{"content":["./components/**/*.{js,vue,ts}","./layouts/**/*.vue","./pages/**/*.vue","./plugins/**/*.{js,ts}","./app.vue"],"theme":{"extend":{"colors":{"primary":{"DEFAULT":"#0052CC","dark":"#003d99"},"accent":{"DEFAULT":"#5a3a7a","light":"#7c5294"},"dark":{"DEFAULT":"#0a0e27","lighter":"#1a1f3a"},"text":{"DEFAULT":"#374151","light":"#6b7280"}}}}},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;