// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 8/14/2026, 12:55:07 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/snajeekumar/Downloads/nexora-studio-fixed/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/components/global/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/components/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/layouts/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/plugins/**/*.{js,ts,mjs}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/composables/**/*.{js,ts,mjs}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/utils/**/*.{js,ts,mjs}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/pages/**/*.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/{A,a}pp.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/{E,e}rror.{vue,mjs,js,cjs,mts,ts,cts,tsx,jsx}","/Users/snajeekumar/Downloads/nexora-studio-fixed/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;